name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Using the correct version of the checkout action

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  
          cache: 'npm'

      - name: Install dependencies
        run: npm install  # Installing dependencies
      
      - name: Build project
        run: npm run build  # Building the project

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1  # Using version v1 of the upload-pages-artifact action
        with:
          path: './build'  # Adjust this to your build output directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
